### ISSUE TITLE
How can I add custom icon to widgets?

### ISSUE THREAD

**Issue by MaxShv** [surveyjs/widgets#103]
I see that there is an option to specify an icon name. 
Is it possible to specify the path of the icon? If not, how can I add my own icons?

![image](https://user-images.githubusercontent.com/6601478/50906338-dcdd1300-13f2-11e9-8789-dbe82abaa479.png)

**Comment by dmitrykurmanov** [comment]
@MaxShv hello! Please add `iconName` property to your custom widget config. And then use it in css something line this:
```css
.my-custom-class:before {
    background-image: url( your url );
    content: "";
    background-size: 16px 16px;
    background-repeat: no-repeat;
    background-position: center;
    padding: 8px;
}
```

here an example: https://plnkr.co/edit/uv0tp5GRqSmhk69cwSKZ?p=preview
